-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 10:15:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `katalogknihu0772` DEFAULT CHARACTER SET utf8 ;
USE `katalogknihu0772` ;

-- -----------------------------------------------------
-- Table `mydb`.`kniha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `katalogknihu0772`.`kniha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(60) NOT NULL,
  `Autor` VARCHAR(45) NOT NULL,
  `Zanr` ENUM("Horor", "Romance", "Sci-fi", "Fantasy", "Krimi", "Detektivky") NOT NULL,
  `Popis` TEXT NOT NULL,
  `Obrazek` LONGBLOB NOT NULL,
  `ISBN` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
